server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rest-project-database:3306/student_info?useUnicode=true&characterEncoding=UTF-8
    username: root #数据库用户名
    password: 123456 #数据库密码
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
